apiVersion: v1
kind: ConfigMap
metadata:
  name: flux-runtime-info
  namespace: flux-system
  labels:
    toolkit.fluxcd.io/runtime: "true"
    reconcile.fluxcd.io/watch: Enabled
  annotations:
    kustomize.toolkit.fluxcd.io/ssa: "Merge"
data:
  ARTIFACT_TAG: latest
  ENVIRONMENT: production
  CLUSTER_NAME: homelab
  CLUSTER_DOMAIN: southcity.dev
  ARTIFACT_SUBJECT_WORKFLOW: push-artifact
  ARTIFACT_SUBJECT_GIT_REF: refs/heads/main
  LOAD_BALANCER_IP_RANGE: 10.0.30.192/26
